services:
  mern-stack:
    container_name: mern-stack
    image: node:lts-slim
    ports:
      - "3000:3000"
    volumes:
      - ${PRJ_PATH}:/home/root/project
      - ./entrypoint.sh:/home/root/project/entrypoint.sh
    working_dir: /home/root/project
    command: ./entrypoint.sh